# Generated by Django 3.0.7 on 2020-12-10 21:32

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('sku', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('image', models.CharField(blank=True, max_length=150)),
                ('descrption', models.CharField(blank=True, max_length=150)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
